// vue/src/components/plan/MealPlanSection.vue
<script setup lang="ts">
import { ref, computed } from 'vue'

interface Meal {
  type: string
  rationale: string
  name: string
  ingredients: string[]
  instructions: string
  nutrition: { calories: string; protein: string; carbs: string; fat: string; vitaminD: string; b12: string; omega3: string }
}

const days = [
  { label: 'Day 1', meals: [] as Meal[] },
  { label: 'Day 2', meals: [] as Meal[] },
  { label: 'Day 3', meals: [] as Meal[] },
  { label: 'Day 4', meals: [] as Meal[] },
  { label: 'Day 5', meals: [] as Meal[] },
  { label: 'Day 6', meals: [] as Meal[] },
  { label: 'Day 7', meals: [] as Meal[] },
]

const day1Meals: Meal[] = [
  {
    type: 'BREAKFAST',
    rationale: 'High in healthy fats and fiber to stabilize morning blood sugar.',
    name: 'Avocado Toast with Poached Egg',
    ingredients: ['2 slices whole-grain bread', '1 ripe avocado', '2 eggs', 'Pinch of sea salt & black pepper', 'Red pepper flakes'],
    instructions: 'Toast the bread until golden. Mash avocado with salt and pepper, spread onto toast. Poach eggs in simmering water for 3 minutes. Place eggs on toast and finish with red pepper flakes.',
    nutrition: { calories: '420 kcal', protein: '18g', carbs: '38g', fat: '24g', vitaminD: '1.1 µg', b12: '0.9 µg', omega3: '0.3g' },
  },
]
days[0]!.meals = day1Meals

const selectedDay = ref(0)
const currentMeals = computed(() => days[selectedDay.value]?.meals ?? [])
</script>

<template>
  <div class="space-y-5">
    <p class="text-sm text-muted-foreground">
      7-Day Meal Plan: Focuses on heart-healthy fats, lean protein, and a variety of
      micronutrients for metabolic support.
    </p>
    <div class="flex gap-2 flex-wrap">
      <button
        v-for="(day, i) in days"
        :key="i"
        type="button"
        class="px-4 py-1.5 rounded-md text-sm font-medium transition-colors"
        :class="selectedDay === i ? 'bg-kwilt-peach text-foreground' : 'border border-border bg-white text-foreground hover:bg-secondary'"
        @click="selectedDay = i"
      >
        {{ day.label }}
      </button>
    </div>
    <div class="bg-white rounded-xl p-6 shadow-soft">
      <h3 class="font-heading text-2xl font-light text-foreground mb-6">Today's agenda</h3>
      <div v-for="(meal, idx) in currentMeals" :key="idx" class="space-y-4">
        <div class="bg-secondary/80 rounded-md px-4 py-2">
          <span class="text-xs font-bold uppercase tracking-wider text-foreground">{{ meal.type }}</span>
          <span class="text-xs text-muted-foreground ml-2">{{ meal.rationale }}</span>
        </div>
        <h4 class="font-heading text-xl font-medium text-foreground">{{ meal.name }}</h4>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div class="space-y-4">
            <div>
              <h5 class="text-xs font-medium uppercase tracking-wider text-muted-foreground mb-2">Ingredients</h5>
              <ul class="space-y-1.5">
                <li v-for="(item, i) in meal.ingredients" :key="i" class="text-sm text-foreground flex items-start gap-2">
                  <span class="w-1 h-1 rounded-full bg-foreground/40 shrink-0 mt-1.5" />
                  {{ item }}
                </li>
              </ul>
            </div>
            <div>
              <h5 class="text-xs font-medium uppercase tracking-wider text-muted-foreground mb-2">Instructions</h5>
              <p class="text-sm text-foreground/80 leading-relaxed">{{ meal.instructions }}</p>
            </div>
          </div>
          <div>
            <h5 class="text-xs font-medium uppercase tracking-wider text-muted-foreground mb-2">Nutrition</h5>
            <div class="space-y-0">
              <div v-for="row in [['Calories', meal.nutrition.calories], ['Protein', meal.nutrition.protein], ['Carbs', meal.nutrition.carbs], ['Fat', meal.nutrition.fat], ['Vitamin D', meal.nutrition.vitaminD], ['B12', meal.nutrition.b12], ['Omega-3', meal.nutrition.omega3]]" :key="row[0]" class="flex justify-between py-2 text-sm border-b border-border last:border-0">
                <span class="text-muted-foreground">{{ row[0] }}</span>
                <span class="font-medium text-foreground">{{ row[1] }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-8 pt-6">
      <p class="text-sm font-semibold text-foreground mb-3">©2025 kwilthealth</p>
      <p class="text-xs text-foreground/70 leading-relaxed">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a nisi in enim consectetur varius. In lacinia eleifend magna porttitor pretium. Aenean nec bibendum felis, eget tincidunt libero. Sed at diam in massa pretium sollicitudin eleifend nec risus. Praesent sed neque a dolor vestibulum molestie sit amet nec massa. Nunc id fringilla diam. Etiam eget volutpat enim. Donec accumsan, lectus in tristique pharetra, massa mauris rhoncus enim, vitae tempus sapien mauris id enim.
      </p>
    </div>
  </div>
</template>

// react/src/components/plan/MealPlanSection.tsx
import { useState, useEffect, useCallback } from "react";
import { mealPlanData, type Meal } from "@/data/mealPlanData";
import { VoiceMicButton } from "@/components/assessment/VoiceMicButton";
import { ArrowRight, ChevronLeft, ChevronRight } from "lucide-react";
import useEmblaCarousel from "embla-carousel-react";
import { useIsMobile } from "@/hooks/use-mobile";

function NutritionTable({ nutrition }: { nutrition: Meal["nutrition"] }) {
  const rows = [
    { label: "Calories", value: nutrition.calories },
    { label: "Protein", value: nutrition.protein },
    { label: "Carbs", value: nutrition.carbs },
    { label: "Fat", value: nutrition.fat },
    { label: "Vitamin D", value: nutrition.vitaminD },
    { label: "B12", value: nutrition.b12 },
    { label: "Omega-3", value: nutrition.omega3 },
  ];

  return (
    <div>
      {rows.map((row, i) => (
        <div
          key={row.label}
          className={`flex justify-between py-2 text-sm ${
            i < rows.length - 1 ? "border-b border-border" : ""
          }`}
        >
          <span className="text-muted-foreground">{row.label}</span>
          <span className="font-medium text-foreground">{row.value}</span>
        </div>
      ))}
    </div>
  );
}

function MealCard({ meal }: { meal: Meal }) {
  return (
    <div className="space-y-4">
      {/* Meal header bar */}
      <div className="bg-secondary/80 rounded-md px-4 py-2">
        <span className="text-xs font-bold uppercase tracking-wider text-foreground">
          {meal.type}
        </span>
        <span className="text-xs text-muted-foreground ml-2">{meal.rationale}</span>
      </div>

      {/* Recipe title */}
      <h4 className="font-heading text-xl font-medium text-foreground">{meal.name}</h4>

      {/* Two-column layout */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Left: Ingredients + Instructions */}
        <div className="space-y-4">
          <div>
            <h5 className="text-xs font-medium uppercase tracking-wider text-muted-foreground mb-2">
              Ingredients
            </h5>
            <ul className="space-y-1.5">
              {meal.ingredients.map((item, i) => (
                <li key={i} className="text-sm text-foreground flex items-start gap-2">
                  <span className="w-1 h-1 rounded-full bg-foreground/40 shrink-0 mt-1.5" />
                  {item}
                </li>
              ))}
            </ul>
          </div>
          <div>
            <h5 className="text-xs font-medium uppercase tracking-wider text-muted-foreground mb-2">
              Instructions
            </h5>
            <p className="text-sm text-foreground/80 leading-relaxed">{meal.instructions}</p>
          </div>
        </div>

        {/* Right: Nutrition */}
        <div>
          <h5 className="text-xs font-medium uppercase tracking-wider text-muted-foreground mb-2">
            Nutrition
          </h5>
          <NutritionTable nutrition={meal.nutrition} />
        </div>
      </div>
    </div>
  );
}

function MealAgenda({ meals }: { meals: Meal[] }) {
  const isMobile = useIsMobile();
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true });
  const [activeIndex, setActiveIndex] = useState(0);

  const onSelect = useCallback(() => {
    if (!emblaApi) return;
    setActiveIndex(emblaApi.selectedScrollSnap());
  }, [emblaApi]);

  useEffect(() => {
    if (!emblaApi) return;
    onSelect();
    emblaApi.on("select", onSelect);
    return () => { emblaApi.off("select", onSelect); };
  }, [emblaApi, onSelect]);

  return (
    <div className="bg-white rounded-xl p-6 shadow-soft">
      <div className="mb-6">
        <div className="flex items-center justify-between">
          <h3 className="font-heading text-2xl font-light text-foreground">Today's agenda</h3>
          {isMobile && (
            <div className="flex gap-1">
              <button
                onClick={() => emblaApi?.scrollPrev()}
                className="p-1.5 rounded-md bg-secondary text-foreground/60 hover:text-foreground transition-colors"
              >
                <ChevronLeft className="h-4 w-4" />
              </button>
              <button
                onClick={() => emblaApi?.scrollNext()}
                className="p-1.5 rounded-md bg-secondary text-foreground/60 hover:text-foreground transition-colors"
              >
                <ChevronRight className="h-4 w-4" />
              </button>
            </div>
          )}
        </div>
        {isMobile && (
          <div className="flex gap-1.5 mt-2 justify-end">
            {meals.map((_, i) => (
              <span
                key={i}
                className={`h-1.5 rounded-full transition-all ${
                  i === activeIndex ? "w-4 bg-foreground" : "w-1.5 bg-foreground/20"
                }`}
              />
            ))}
          </div>
        )}
      </div>

      {isMobile ? (
        <div className="overflow-hidden -mx-2" ref={emblaRef}>
          <div className="flex">
            {meals.map((meal, i) => (
              <div key={i} className="flex-[0_0_100%] min-w-0 px-2">
                <MealCard meal={meal} />
              </div>
            ))}
          </div>
        </div>
      ) : (
        <div className="space-y-8">
          {meals.map((meal, i) => (
            <MealCard key={i} meal={meal} />
          ))}
        </div>
      )}
    </div>
  );
}

const symptoms = [
  "No symptoms", "Bloating", "Nausea", "Fatigue", "Heartburn",
  "Brain fog", "Loose stool", "Constipation", "Skin flushing / Itching",
  "Increased thirst", "Other",
];

export default function MealPlanSection() {
  const [selectedDay, setSelectedDay] = useState(0);
  const [selectedSymptoms, setSelectedSymptoms] = useState<string[]>([]);
  const [feedbackText, setFeedbackText] = useState("");
  const currentDay = mealPlanData[selectedDay];

  const toggleSymptom = (s: string) =>
    setSelectedSymptoms((prev) =>
      prev.includes(s) ? prev.filter((x) => x !== s) : [...prev, s]
    );

  return (
    <div className="space-y-5">
      {/* Section header */}
      <p className="text-sm text-muted-foreground">
        7-Day Meal Plan: Focuses on heart-healthy fats, lean protein, and a variety of
        micronutrients for metabolic support.
      </p>

      {/* Day selector chips */}
      <div className="flex gap-2 flex-wrap">
        {mealPlanData.map((day, i) => (
          <button
            key={i}
            onClick={() => setSelectedDay(i)}
            className={`px-4 py-1.5 rounded-md text-sm font-medium transition-colors ${
              selectedDay === i
                ? "bg-kwilt-peach text-foreground"
                : "border border-border bg-white text-foreground hover:bg-secondary"
            }`}
          >
            {day.label}
          </button>
        ))}
      </div>

      {/* Today's agenda card */}
      <MealAgenda meals={currentDay.meals} />

      {/* Feedback section */}
      <div className="space-y-3">
        <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
          Feedback
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* Left: Symptoms */}
          <div className="bg-secondary rounded-xl p-6">
            <h3 className="font-heading text-2xl font-light text-foreground mb-5">
              Any symptoms after meals?
            </h3>
            <div className="flex flex-wrap gap-2">
              {symptoms.map((s) => (
                <button
                  key={s}
                  onClick={() => toggleSymptom(s)}
                  className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${
                    selectedSymptoms.includes(s)
                      ? "bg-kwilt-peach text-foreground"
                      : "bg-white border border-border text-foreground hover:bg-white/80"
                  }`}
                >
                  {s}
                </button>
              ))}
            </div>
          </div>

          {/* Right: Open text feedback */}
          <div className="bg-secondary rounded-xl p-6 flex flex-col">
            <h3 className="font-heading text-2xl font-light text-foreground mb-2">
              Your input matters
            </h3>
            <p className="text-sm text-muted-foreground mb-4">
              Let us know what felt off, overwhelming, or just didn't fit your lifestyle.
              We'll use your feedback to fine-tune your plan and make sure it works better for you.
            </p>
            <div className="relative flex-1 min-h-[160px]">
              <textarea
                value={feedbackText}
                onChange={(e) => setFeedbackText(e.target.value)}
                placeholder="Inputs will be used to adapt next plan"
                className="w-full h-full min-h-[160px] rounded-lg bg-white border-none px-4 py-3 text-sm text-foreground placeholder:text-muted-foreground resize-none focus:outline-none focus:ring-2 focus:ring-ring"
              />
              <div className="absolute top-2 right-2">
                <VoiceMicButton
                  onResult={(text) =>
                    setFeedbackText((prev) => (prev ? prev + " " + text : text))
                  }
                />
              </div>
            </div>
            <div className="flex justify-end mt-3">
              <button className="link-arrow text-foreground text-sm">
                SEND <ArrowRight className="h-4 w-4" />
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Footer disclaimer */}
      <div className="mt-8 pt-6">
        <p className="text-sm font-semibold text-foreground mb-3">©2025 kwilthealth</p>
        <p className="text-xs text-foreground/70 leading-relaxed">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a nisi in enim consectetur varius. In lacinia eleifend magna porttitor pretium. Aenean nec bibendum felis, eget tincidunt libero. Sed at diam in massa pretium sollicitudin eleifend nec risus. Praesent sed neque a dolor vestibulum molestie sit amet nec massa. Nunc id fringilla diam. Etiam eget volutpat enim. Donec accumsan, lectus in tristique pharetra, massa mauris rhoncus enim, vitae tempus sapien mauris id enim.
        </p>
      </div>
    </div>
  );
}
