// react/src/components/treatments/CancelAppointmentModal.tsx
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertTriangle } from "lucide-react";

interface CancelAppointmentModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  appointmentType?: string;
  appointmentDate?: string;
}

export function CancelAppointmentModal({ open, onOpenChange, appointmentType, appointmentDate }: CancelAppointmentModalProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[400px] p-6 gap-0" style={{ background: "#F5F1F0" }}>
        <DialogHeader className="pb-4">
          <DialogTitle className="font-heading text-xl font-medium text-foreground">
            Cancel Appointment
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-5">
          <div className="flex items-start gap-3 rounded-xl border border-border bg-background p-4">
            <AlertTriangle className="h-5 w-5 text-muted-foreground flex-none mt-0.5" />
            <div>
              <p className="text-sm font-medium">Are you sure you want to cancel?</p>
              <p className="text-sm text-muted-foreground mt-1">
                {appointmentType && <span className="font-medium text-foreground">{appointmentType}</span>}
                {appointmentDate && <span> on {appointmentDate}</span>}
              </p>
              <p className="text-xs text-muted-foreground mt-2">This action cannot be undone. You will need to book a new appointment.</p>
            </div>
          </div>

          <div className="flex gap-3">
            <button
              onClick={() => onOpenChange(false)}
              className="flex-1 rounded-md border border-border bg-background py-3 text-sm font-light text-foreground hover:bg-muted transition-colors"
            >
              Keep Appointment
            </button>
            <button
              onClick={() => onOpenChange(false)}
              className="flex-1 rounded-md bg-foreground py-3 text-sm font-light text-background hover:opacity-90 transition-opacity"
            >
              Yes, Cancel
            </button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

// vue/src/components/treatments/CancelAppointmentModal.vue
<script setup lang="ts">
import UiDialog from '@/components/ui/dialog.vue'
import UiButton from '@/components/ui/button.vue'

defineProps<{ open: boolean; appointmentType?: string; appointmentDate?: string }>()
const emit = defineEmits<{ 'update:open': [v: boolean] }>()
</script>

<template>
  <UiDialog :open="open" @update:open="(v: unknown) => emit('update:open', v as boolean)">
    <div class="sm:max-w-[400px] p-6 gap-0" style="background: #F5F1F0">
      <div class="pb-4">
        <h2 class="font-heading text-xl font-medium text-foreground">Cancel Appointment</h2>
      </div>
      <div class="space-y-5">
        <div class="flex items-start gap-3 rounded-xl border border-border bg-background p-4">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-muted-foreground flex-none mt-0.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/><path d="M12 9v4"/><path d="M12 17h.01"/></svg>
          <div>
            <p class="text-sm font-medium">Are you sure you want to cancel?</p>
            <p class="text-sm text-muted-foreground mt-1">
              <span v-if="appointmentType" class="font-medium text-foreground">{{ appointmentType }}</span>
              <span v-if="appointmentDate"> on {{ appointmentDate }}</span>
            </p>
            <p class="text-xs text-muted-foreground mt-2">This action cannot be undone. You will need to book a new appointment.</p>
          </div>
        </div>
        <div class="flex gap-3">
          <UiButton variant="outline" class="flex-1 py-3" @click="emit('update:open', false)">Keep Appointment</UiButton>
          <UiButton class="flex-1 rounded-md bg-foreground py-3 text-sm font-light text-background hover:opacity-90" @click="emit('update:open', false)">Yes, Cancel</UiButton>
        </div>
      </div>
    </div>
  </UiDialog>
</template>
