// react/src/components/treatments/RescheduleModal.tsx
import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Calendar } from "@/components/ui/calendar";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Clock } from "lucide-react";
import { cn } from "@/lib/utils";

interface RescheduleModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

const timeSlots = [
  "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM",
  "11:00 AM", "11:30 AM", "12:00 PM",
  "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM",
  "3:00 PM", "3:30 PM", "4:00 PM", "4:30 PM",
];

export function RescheduleModal({ open, onOpenChange }: RescheduleModalProps) {
  const [date, setDate] = useState<Date | undefined>(undefined);
  const [time, setTime] = useState("");

  const handleReschedule = () => {
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent
        className="sm:max-w-[440px] p-6 gap-0 max-h-[90vh] overflow-y-auto"
        style={{ background: "#F5F1F0" }}
      >
        <DialogHeader className="pb-4">
          <DialogTitle className="font-heading text-xl font-medium text-foreground">
            Reschedule Appointment
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-5">
          {/* Date */}
          <div className="space-y-2">
            <label className="text-sm font-medium text-foreground">Select New Date</label>
            <div className="bg-white rounded-md p-2">
              <Calendar
                mode="single"
                selected={date}
                onSelect={setDate}
                disabled={(d) => d < new Date()}
                className={cn("p-2 pointer-events-auto w-full [&_table]:w-full [&_td]:w-[14.28%] [&_th]:w-[14.28%] [&_.rdp-head_row]:w-full [&_.rdp-tbody]:w-full [&_.rdp-caption]:flex [&_.rdp-caption]:justify-between [&_.rdp-caption]:w-full [&_.rdp-nav]:flex [&_.rdp-nav]:gap-1")}
              />
            </div>
          </div>

          {/* Time */}
          <div className="space-y-2">
            <label className="text-sm font-medium text-foreground">Preferred Time</label>
            <Select value={time} onValueChange={setTime}>
              <SelectTrigger className="w-full bg-white border-border rounded-md">
                <SelectValue placeholder="Select Time" />
              </SelectTrigger>
              <SelectContent className="bg-white z-50">
                {timeSlots.map((t) => (
                  <SelectItem key={t} value={t}>
                    <span className="flex items-center gap-2">
                      <Clock className="h-3.5 w-3.5" />
                      {t}
                    </span>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Confirm button */}
          <button
            onClick={handleReschedule}
            className="w-full rounded-md bg-primary py-3.5 text-sm font-light text-foreground hover:bg-primary/90 transition-colors flex items-center justify-center gap-2"
          >
            <Clock className="h-4 w-4" />
            Confirm Reschedule
          </button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

// vue/src/components/treatments/RescheduleModal.vue
<script setup lang="ts">
import { ref } from 'vue'
import UiDialog from '@/components/ui/dialog.vue'
import UiButton from '@/components/ui/button.vue'

defineProps<{ open: boolean }>()
const emit = defineEmits<{ 'update:open': [v: boolean] }>()

const timeSlots = ['9:00 AM', '9:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM', '12:00 PM', '1:00 PM', '1:30 PM', '2:00 PM', '2:30 PM', '3:00 PM', '3:30 PM', '4:00 PM', '4:30 PM']
const date = ref('')
const time = ref('')

function close() {
  emit('update:open', false)
}
</script>

<template>
  <UiDialog :open="open" @update:open="(v: unknown) => emit('update:open', v as boolean)">
    <div class="sm:max-w-[440px] p-6 gap-0 max-h-[90vh] overflow-y-auto" style="background: #F5F1F0">
      <div class="pb-4">
        <h2 class="font-heading text-xl font-medium text-foreground">Reschedule Appointment</h2>
      </div>
      <div class="space-y-5">
        <div class="space-y-2">
          <label class="text-sm font-medium text-foreground">Select New Date</label>
          <input v-model="date" type="date" class="w-full rounded-md border border-border bg-white px-3 py-2 text-sm" :min="new Date().toISOString().slice(0,10)" />
        </div>
        <div class="space-y-2">
          <label class="text-sm font-medium text-foreground">Select New Time</label>
          <select v-model="time" class="w-full rounded-md border border-border bg-white px-3 py-2 text-sm">
            <option value="">Select</option>
            <option v-for="t in timeSlots" :key="t" :value="t">{{ t }}</option>
          </select>
        </div>
        <UiButton class="w-full rounded-md bg-primary py-3 text-sm font-light text-foreground hover:bg-primary/90" @click="close">Confirm Reschedule</UiButton>
      </div>
    </div>
  </UiDialog>
</template>
