// react/src/components/signup/DobPicker.tsx
import { useState } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { format, getDaysInMonth, startOfMonth, getDay, isAfter, isSameDay } from "date-fns";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { cn } from "@/lib/utils";

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

const currentYear = new Date().getFullYear();
const YEARS = Array.from({ length: currentYear - 1919 }, (_, i) => currentYear - 1 - i);

interface DobPickerProps {
  value: Date | undefined;
  onChange: (date: Date) => void;
  inputClass?: string;
}

export function DobPicker({ value, onChange, inputClass = "" }: DobPickerProps) {
  const today = new Date();
  const [open, setOpen] = useState(false);
  const [viewYear, setViewYear] = useState(value?.getFullYear() ?? 1990);
  const [viewMonth, setViewMonth] = useState(value?.getMonth() ?? 0);

  const daysInMonth = getDaysInMonth(new Date(viewYear, viewMonth, 1));
  const firstDayOfWeek = getDay(startOfMonth(new Date(viewYear, viewMonth, 1)));

  // Pad with previous month's trailing days
  const leadingBlanks = firstDayOfWeek;
  const totalCells = Math.ceil((leadingBlanks + daysInMonth) / 7) * 7;

  const prevMonth = () => {
    if (viewMonth === 0) { setViewMonth(11); setViewYear(v => v - 1); }
    else setViewMonth(m => m - 1);
  };
  const nextMonth = () => {
    if (viewMonth === 11) { setViewMonth(0); setViewYear(v => v + 1); }
    else setViewMonth(m => m + 1);
  };

  const handleDayClick = (day: number) => {
    const selected = new Date(viewYear, viewMonth, day);
    if (isAfter(selected, today)) return;
    onChange(selected);
    setOpen(false);
  };

  const selectClass =
    "h-9 rounded-md border border-border bg-card px-3 text-sm text-foreground appearance-none cursor-pointer focus:outline-none focus:ring-1 focus:ring-primary";

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <button
          type="button"
          className={cn(
            inputClass,
            "flex items-center justify-between w-full text-left",
            !value && "text-foreground/30"
          )}
        >
          {value ? format(value, "MM/dd/yyyy") : "MM/DD/YYYY"}
          <svg width="15" height="15" viewBox="0 0 15 15" fill="none" className="text-foreground shrink-0">
            <path d="M4.5 1V3M10.5 1V3M1 5.5H14M2.5 2.5H12.5C13.05 2.5 13.5 2.95 13.5 3.5V12.5C13.5 13.05 13.05 13.5 12.5 13.5H2.5C1.95 13.5 1.5 13.05 1.5 12.5V3.5C1.5 2.95 1.95 2.5 2.5 2.5Z" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
        </button>
      </PopoverTrigger>

      <PopoverContent
        className="w-[300px] p-0 z-50 bg-card border border-border shadow-xl rounded-lg overflow-hidden"
        align="start"
        sideOffset={4}
      >
        {/* Year + Month dropdowns */}
        <div className="flex gap-2 p-3 border-b border-border bg-card">
          <div className="relative flex-1">
            <select
              className={selectClass + " w-full pr-7"}
              value={viewYear}
              onChange={e => setViewYear(Number(e.target.value))}
            >
              {YEARS.map(y => (
                <option key={y} value={y}>{y}</option>
              ))}
            </select>
            <ChevronRight size={12} className="absolute right-2 top-1/2 -translate-y-1/2 rotate-90 text-foreground pointer-events-none" />
          </div>
          <div className="relative flex-1">
            <select
              className={selectClass + " w-full pr-7"}
              value={viewMonth}
              onChange={e => setViewMonth(Number(e.target.value))}
            >
              {MONTHS.map((m, i) => (
                <option key={m} value={i}>{m}</option>
              ))}
            </select>
            <ChevronRight size={12} className="absolute right-2 top-1/2 -translate-y-1/2 rotate-90 text-foreground pointer-events-none" />
          </div>
        </div>

        {/* Month title + prev/next arrows */}
        <div className="flex items-center justify-between px-4 py-2.5">
          <button
            type="button"
            onClick={prevMonth}
            className="p-1 rounded hover:bg-background transition-colors text-foreground hover:text-foreground"
          >
            <ChevronLeft size={16} />
          </button>
          <span className="text-sm font-semibold text-foreground">
            {MONTHS[viewMonth]} {viewYear}
          </span>
          <button
            type="button"
            onClick={nextMonth}
            className="p-1 rounded hover:bg-background transition-colors text-foreground hover:text-foreground"
          >
            <ChevronRight size={16} />
          </button>
        </div>

        {/* Day of week headers */}
        <div className="grid grid-cols-7 px-3 pb-1">
          {["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"].map(d => (
            <div key={d} className="text-center text-[11px] font-semibold text-foreground py-1">
              {d}
            </div>
          ))}
        </div>

        {/* Day grid */}
        <div className="grid grid-cols-7 px-3 pb-3 gap-y-0.5">
          {Array.from({ length: totalCells }, (_, i) => {
            const day = i - leadingBlanks + 1;
            const isCurrentMonth = day >= 1 && day <= daysInMonth;
            const cellDate = new Date(viewYear, viewMonth, day);
            const isFuture = isAfter(cellDate, today);
            const isSelected = value && isSameDay(cellDate, value);

            return (
              <button
                key={i}
                type="button"
                disabled={!isCurrentMonth || isFuture}
                onClick={() => isCurrentMonth && handleDayClick(day)}
                className={cn(
                  "h-8 w-full text-sm rounded-md transition-colors flex items-center justify-center",
                  !isCurrentMonth && "text-foreground/20 cursor-default",
                  isCurrentMonth && !isFuture && !isSelected &&
                    "text-foreground hover:bg-primary/10 cursor-pointer",
                  isCurrentMonth && isFuture && "text-foreground/25 cursor-not-allowed",
                  isSelected &&
                    "bg-primary text-primary-foreground font-semibold hover:bg-primary/90"
                )}
              >
                {isCurrentMonth ? day : ""}
              </button>
            );
          })}
        </div>
      </PopoverContent>
    </Popover>
  );
}

// vue/src/components/signup/DobPicker.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { cn } from '@/lib/utils'
import UiPopover from '@/components/ui/popover.vue'

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
const currentYear = new Date().getFullYear()
const YEARS = Array.from({ length: currentYear - 1919 }, (_, i) => currentYear - 1 - i)

const props = withDefaults(
  defineProps<{ modelValue?: Date; inputClass?: string }>(),
  { inputClass: '' }
)
const emit = defineEmits<{ 'update:modelValue': [date: Date] }>()

const open = ref(false)
const viewYear = ref(props.modelValue?.getFullYear() ?? 1990)
const viewMonth = ref(props.modelValue?.getMonth() ?? 0)

watch(() => props.modelValue, (v) => {
  if (v) {
    viewYear.value = v.getFullYear()
    viewMonth.value = v.getMonth()
  }
})

function getDaysInMonth(y: number, m: number) {
  return new Date(y, m + 1, 0).getDate()
}
function getFirstDayOfWeek(y: number, m: number) {
  return new Date(y, m, 1).getDay()
}

const daysInMonth = computed(() => getDaysInMonth(viewYear.value, viewMonth.value))
const firstDayOfWeek = computed(() => getFirstDayOfWeek(viewYear.value, viewMonth.value))
const leadingBlanks = computed(() => firstDayOfWeek.value)
const totalCells = computed(() => Math.ceil((leadingBlanks.value + daysInMonth.value) / 7) * 7)

function prevMonth() {
  if (viewMonth.value === 0) {
    viewMonth.value = 11
    viewYear.value -= 1
  } else {
    viewMonth.value -= 1
  }
}
function nextMonth() {
  if (viewMonth.value === 11) {
    viewMonth.value = 0
    viewYear.value += 1
  } else {
    viewMonth.value += 1
  }
}

const today = new Date()
today.setHours(23, 59, 59, 999)

function isAfter(d: Date) {
  return d.getTime() > today.getTime()
}
function isSameDay(a: Date, b: Date) {
  return a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate()
}

function handleDayClick(day: number) {
  const selected = new Date(viewYear.value, viewMonth.value, day)
  if (isAfter(selected)) return
  emit('update:modelValue', selected)
  open.value = false
}

const displayValue = computed(() => {
  const v = props.modelValue
  if (!v) return 'MM/DD/YYYY'
  const mm = String(v.getMonth() + 1).padStart(2, '0')
  const dd = String(v.getDate()).padStart(2, '0')
  const yyyy = v.getFullYear()
  return `${mm}/${dd}/${yyyy}`
})

const selectClass = 'h-9 rounded-md border border-border bg-card px-3 text-sm text-foreground appearance-none cursor-pointer focus:outline-none focus:ring-1 focus:ring-primary'

interface Cell {
  day: number
  isCurrentMonth: boolean
  isFuture: boolean
  isSelected: boolean
}
const cells = computed<Cell[]>(() => {
  const out: Cell[] = []
  for (let i = 0; i < totalCells.value; i++) {
    const day = i - leadingBlanks.value + 1
    const isCurrentMonth = day >= 1 && day <= daysInMonth.value
    const cellDate = new Date(viewYear.value, viewMonth.value, day)
    const isFuture = isAfter(cellDate)
    const isSelected = !!props.modelValue && isSameDay(cellDate, props.modelValue)
    out.push({ day, isCurrentMonth, isFuture, isSelected })
  }
  return out
})

function cellClass(c: Cell) {
  if (!c.isCurrentMonth) return 'text-foreground/20 cursor-default'
  if (c.isFuture) return 'text-foreground/25 cursor-not-allowed'
  if (c.isSelected) return 'bg-primary text-primary-foreground font-semibold hover:bg-primary/90'
  return 'text-foreground hover:bg-primary/10 cursor-pointer'
}
</script>

<template>
  <UiPopover v-model:open="open" class="w-full">
    <template #trigger>
      <button
        type="button"
        :class="cn(props.inputClass, 'flex items-center justify-between w-full text-left', !modelValue && 'text-foreground/30')"
      >
        {{ displayValue }}
        <svg width="15" height="15" viewBox="0 0 15 15" fill="none" class="text-foreground shrink-0">
          <path d="M4.5 1V3M10.5 1V3M1 5.5H14M2.5 2.5H12.5C13.05 2.5 13.5 2.95 13.5 3.5V12.5C13.5 13.05 13.05 13.5 12.5 13.5H2.5C1.95 13.5 1.5 13.05 1.5 12.5V3.5C1.5 2.95 1.95 2.5 2.5 2.5Z" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </button>
    </template>
    <div class="w-[300px] p-0 z-50 bg-card border border-border shadow-xl rounded-lg overflow-hidden">
      <div class="flex gap-2 p-3 border-b border-border bg-card">
        <div class="relative flex-1">
          <select
            :value="viewYear"
            class="w-full pr-7"
            :class="selectClass"
            @change="viewYear = Number(($event.target as HTMLSelectElement).value)"
          >
            <option v-for="y in YEARS" :key="y" :value="y">{{ y }}</option>
          </select>
        </div>
        <div class="relative flex-1">
          <select
            :value="viewMonth"
            class="w-full pr-7"
            :class="selectClass"
            @change="viewMonth = Number(($event.target as HTMLSelectElement).value)"
          >
            <option v-for="(m, i) in MONTHS" :key="m" :value="i">{{ m }}</option>
          </select>
        </div>
      </div>
      <div class="flex items-center justify-between px-4 py-2.5">
        <button type="button" class="p-1 rounded hover:bg-background transition-colors text-foreground hover:text-foreground" @click="prevMonth">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="15 18 9 12 15 6"/></svg>
        </button>
        <span class="text-sm font-semibold text-foreground">{{ MONTHS[viewMonth] }} {{ viewYear }}</span>
        <button type="button" class="p-1 rounded hover:bg-background transition-colors text-foreground hover:text-foreground" @click="nextMonth">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="9 18 15 12 9 6"/></svg>
        </button>
      </div>
      <div class="grid grid-cols-7 px-3 pb-1">
        <div v-for="d in ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa']" :key="d" class="text-center text-[11px] font-semibold text-foreground py-1">{{ d }}</div>
      </div>
      <div class="grid grid-cols-7 px-3 pb-3 gap-y-0.5">
        <button
          v-for="(c, i) in cells"
          :key="i"
          type="button"
          :disabled="!c.isCurrentMonth || c.isFuture"
          :class="cn('h-8 w-full text-sm rounded-md transition-colors flex items-center justify-center', cellClass(c))"
          @click="c.isCurrentMonth && !c.isFuture && handleDayClick(c.day)"
        >
          {{ c.isCurrentMonth ? c.day : '' }}
        </button>
      </div>
    </div>
  </UiPopover>
</template>
